package com.cqin.sms.model;

import javafx.scene.control.CheckBox;
import lombok.Getter;
import lombok.Setter;

@Getter
public class Product {
    private int productID;
    private @Setter String productName;
    private @Setter String productCategory;
    private @Setter int remainingStock;
    private @Setter double unitPrice;
    private @Setter CheckBox checkBox;

    public Product() {
        //For searching purpose, a product with -1 id indicates that the product does not exist
        productID = -1;
    }

    public Product(int productID, String productName, String productCategory, int remainingStock, double unitPrice) {
        this.productID = productID;
        this.productName = productName;
        this.productCategory = productCategory;
        this.remainingStock = remainingStock;
        this.unitPrice = unitPrice;
        this.checkBox = new CheckBox();
    }

    public Product(String productName, String productCategory, int remainingStock, double unitPrice) {
        //When user adds a product, prodID is not required as it is automatically generated by database
        this.productName = productName;
        this.productCategory = productCategory;
        this.remainingStock = remainingStock;
        this.unitPrice = unitPrice;
        this.checkBox = new CheckBox();
    }
}
